In [5]:
import os
#os.chdir(r'C:\\Users\\floor\\Documents\\Studie\\Master Technical Medicine\\TM jaar 3\\Afstuderen\\ICK sleep project')
import pandas as pd
import pyedflib
import numpy as np
#from src.process_raw_data.EDFfiles import load_edf_file
#from main import print_hi
#from settings import RAW_DATA, INPUT_DATA

# https://pyedflib.readthedocs.io/en/latest/ref/highlevel.html#pyedflib.highlevel.anonymize_edf

#### 1. inladen data

In [17]:
data_path = r'C:\Users\floor\Documents\Studie\Master Technical Medicine\TM jaar 3\Afstuderen\ICK_sleep_project\data\1_raw_data\EDF_test_files'

#edf_file  = r'C:\Users\floor\Documents\Studie\Master Technical Medicine\TM jaar 3\Afstuderen\EDF files\ins6.edf'
edf_file = os.path.join(data_path, '1410419_26112020.EDF')
#edf_file = r'C:\Users\floor\Documents\Studie\Master Technical Medicine\TM jaar 3\Afstuderen\EDF files\1410419_26112020.EDF'
#edf_file = r'C:\Users\floor\Documents\Studie\Master Technical Medicine\TM jaar 3\Afstuderen\EDF files\1438646_26112020.EDF'

In [8]:
signals, signal_headers, header = pyedflib.highlevel.read_edf(file_name)

In [22]:

signal_headers
signals

[array([-2060.82246128,  3066.11123827,  3123.33867399, ...,
           10.79118029,    11.37712673,    13.13496605]),
 array([-2180.74616617,  3051.36491951,  3123.14335851, ...,
           10.1075761 ,     9.91226062,    10.00991836]),
 array([-238.82200351, -236.47821775, -235.59929808, ...,    5.90829328,
           5.32234684,    4.15045396]),
 array([-73.68276493,  67.33501183, 268.11932555, ...,   3.17387655,
          2.58793011,   2.29495689]),
 array([-3165.33150225,  2024.20080873,  3123.63164721, ...,
          -12.64667735,    -5.90829328,   -11.47478447]),
 array([-2107.50286107,  3057.4196994 ,  3123.24101625, ...,
            9.52162966,     9.91226062,     9.81460288]),
 array([127., 127., 127., ..., 127., 127., 127.]),
 array([  0.,   0.,   0., ..., 255., 255., 255.]),
 array([-44., -44., -44., ..., -28., -28., -28.]),
 array([3125.19417105, 3125.78011749, 3125.19417105, ...,   43.40886549,
         127.68749523,   72.21789883]),
 array([3123.82696269, 3124.41290913, 

In [23]:
signals[17]
signal_headers[17]

{'label': 'EEG F4',
 'dimension': 'uV',
 'sample_rate': 256,
 'physical_max': 3200.0,
 'physical_min': -3200.0,
 'digital_max': 32767,
 'digital_min': -32768,
 'prefilter': '',
 'transducer': ''}

14469120


2

2. Annomize the files 

In [18]:
pyedflib.highlevel.anonymize_edf(edf_file, new_file=None, to_remove=['patientname', 'birthdate'], new_values=['xxx', ''], verify=False)[source]

TypeError: '>=' not supported between instances of 'bytes' and 'int'